import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";

import "./globals.css";
import WidthWrapper from "@/components/width-wrapper";
import Navbar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";

const jetBrainsMono = JetBrains_Mono({
   subsets: ["latin"],
   weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`${jetBrainsMono.className}  antialiased`}>
            <div className="background-color text-stone-300">
               <Navbar />
               <WidthWrapper>
                  <main>{children}</main>
               </WidthWrapper>
               <Footer />
            </div>
         </body>
      </html>
   );
}
